{{- if .Values.secretProviderClass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "github-metrics.fullname" . }}-spc
  labels:
    {{- include "github-metrics.labels" . | nindent 4 }}
  annotations:
    {{- include "github-metrics.trAnnotations" . | nindent 4 }}
spec:
  provider: {{ .Values.secretProviderClass.provider }}
  parameters:
    objects: |
      - objectName: {{ .Values.secretProviderClass.awsSecretName | quote }}
        objectType: "secretsmanager"
        jmesPath:
          - path: PORT_CLIENT_ID
            objectAlias: PORT_CLIENT_ID
          - path: PORT_CLIENT_SECRET
            objectAlias: PORT_CLIENT_SECRET
          - path: X_GITHUB_APP_ID
            objectAlias: X_GITHUB_APP_ID
          - path: X_GITHUB_APP_INSTALLATION_ID
            objectAlias: X_GITHUB_APP_INSTALLATION_ID
          - path: X_GITHUB_APP_PRIVATE_KEY
            objectAlias: X_GITHUB_APP_PRIVATE_KEY
  secretObjects:
    - secretName: {{ include "github-metrics.secretName" . }}
      type: Opaque
      data:
        - objectName: PORT_CLIENT_ID
          key: PORT_CLIENT_ID
        - objectName: PORT_CLIENT_SECRET
          key: PORT_CLIENT_SECRET
        - objectName: X_GITHUB_APP_ID
          key: X_GITHUB_APP_ID
        - objectName: X_GITHUB_APP_INSTALLATION_ID
          key: X_GITHUB_APP_INSTALLATION_ID
        - objectName: X_GITHUB_APP_PRIVATE_KEY
          key: X_GITHUB_APP_PRIVATE_KEY
{{- end }}
