{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "github-metrics.serviceAccountName" . }}
  labels:
    {{- include "github-metrics.labels" . | nindent 4 }}
  annotations:
    {{- include "github-metrics.trAnnotations" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
