name: collect_workflow_metrics
on:
    workflow_dispatch:
    schedule:
      - cron: '0 12 * * *'
jobs:
    workflow:
      name: workflow_metrics
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: oven-sh/setup-bun@v2
        - run: bun run workflow-metrics
          env: # Or as an environment variable
            X_GITHUB_ORGS: ${{ secrets.X_GITHUB_ORGS }}
            X_GITHUB_ENTERPRISE: ${{ secrets.X_GITHUB_ENTERPRISE }}
            X_GITHUB_TOKEN: ${{ secrets.X_GITHUB_AUTH_TOKEN }},${{ secrets.X_GITHUB_AUTH_TOKEN_2 }},${{ secrets.X_GITHUB_AUTH_TOKEN_3 }}
            PORT_CLIENT_ID: ${{ secrets.PORT_CLIENT_ID }}
            PORT_CLIENT_SECRET: ${{ secrets.PORT_CLIENT_SECRET }}
